### ISSUE TITLE
Improve onboarding for new developers

### ISSUE THREAD

**Issue by joshsmith** [code-corps/deprecated-code-corps-rails-api#152]
A collection of tasks we need to get done:
- [ ] #150 
- [x] #151 
- [x] #149 (awaiting review)
- [x] Add note about testing `http://api.lvh.me:3000/ping` to the README to see that the API works as intended
- [x] Add documentation around `INDEX NOT FOUND` to make clear it's expected behavior, and how it works with `ember deploy`

**Comment by begedin** [comment]
Regarding removing hound integration, that's just a single click from the repository settings page, but do we really wan't it gone completely.

PR #178 adds a `.hound.yml` file, which points to our own, custom `.rubocop.yml`, which, when properly set up, should allow us to avoid too much hound spam, while still forcing the developer to follow style guidelines.

Also, if an outside contributor fork the repo to create a PR, they will not inherit our integrations anyway, from my experience. Even the PR against the main fork will not run any integrations, due to it being defined on the fork repo.

I'm thinking we might want to stick with hound for now and just agree on a set of styles we wish to enforce. We can add those to our `.rubocop.yml` over time.

**Comment by joshsmith** [comment]
Agreed on Hound. Let's keep it.

**Comment by joshsmith** [comment]
Closing in favor of more specific tasks to accomplish this.
