### ISSUE TITLE
Add validation for post type

### ISSUE THREAD

**Issue by joshsmith** [code-corps/deprecated-code-corps-rails-api#165]
There's no validation currently.

**Comment by begedin** [comment]
`post_type` is an enum, meaning when the attribute is set, it expects us to pass it a symbol `[:task, :idea, :progress, :issue]`, but when read directly, it responds with one of `%w(task idea progress issue)`. 

Due to this behavior, we cannot use the following shoulda matchers: `validates_inclusion_of`, `allow_value`, `allow_values`, `not_allow_value`.

Also, by default the enum already behaves in a way that prevents any code from setting the value to any symbol other than the four we defined. If we attempt to set it to anything else, an `ArgumentError` will be raised.

Lastly, we do already check that the enum is defined in `spec/models/post_spec/behavior` with `should_define_enum`.

We could define a validation on the model level, but due to enum behavior, it would never get raised, since the `ArgumentError` would be raised first.

Due to all this, I'm thinking we should give up on trying to make it a validation. The client UI should provide a dropdown/selector of some sort. If the dropdown is badly defined, then there will be an argument error when posting.

**The validation we can and should add is a simple presence validation**, since I don't think we should ever allow a `nil` value for `post_type`
