### ISSUE TITLE
Handle preview markdown/body edge case

### ISSUE THREAD

**Issue by joshsmith** [code-corps/deprecated-code-corps-rails-api#199]
We have an edge case with previewing a post that you're currently editing.

The way our system currently works is that when previewing, the post is saved as a draft. This works fine for the not-yet-published post case. But once a post is published and the user goes to edit it, saving that edit for a preview will expose the edit to everyone.

This is obviously not desired behavior.

My suggestion (and you can suggest something else!) is that we add `markdown_preview` and `body_preview` columns in order to work around this edge case. These columns should maybe be cleared out when an actual edit is persisted.

**Comment by begedin** [comment]
I looked into this a bit, and we definitely have a discrepancy between the client and the API to begin with.

Currently, even with adding the `markdown_preview` and `body_preview` fields, I don't think we would be doing it properly here.

Here's what the flow would be:

### A new post is being created
- User starts writing. They wan't a preview.
- Every time we switch to the preview tab...
  - POST/PATCH request is sent to the server, with post status set to `:draft`. It's POST the first time, PATCH after that.
  - Server takes markdown, generates body and saves the post into the database. It replies with the created post.
  - Client shows post body as preview.
- When the user clicks the "Publish" button on the client
  - Either POST or PATCH is sent to the server (depending on if there were any previews), with status sent to ':published'.
  - Server updates/creates record, sets status to published, and responds with it.
  - Record is now viewable by other users as well, since it isn't a draft anymore.

### An existing post is being edited
- User starts writing. They wan't a preview
-  Every time we switch to the preview tab, what do we do? 
  - Do we send a PATCH request with post status set do draft? In that case, post will be temporarily unavailable to other users, possibly even permanently if user decided to quit then and there. **This is not an option.**
  - Do we leave the status alone, and send a patch request with the markdown_preview instead of the markdown field set to the content? That would work, but I was under the impression we'd likely want a draft history at some point in the future? Was I wrong? 
  - Do we make a draft copy of the post, which, in the future, would allow us  to have draft history?

If we're going with the `_preview` fields, then I would like to simplify things a bit:

## The `_preview` field approach

This is the same for new and edited posts, and applies in a similar way to new and edited comments
- Post/comment has 4 fields - `markdown`, `body`, `markdown_preview`, `body_preview`
- User starts editing/creating
- The ember component for editing is bound to `markdown_preview` and `body_preview` fields to begin with. We never look at the original `markdown` and `body` fields in the edit component. Those are used 
- When a preview is triggered on the client, we send a `preview: true` parameter along with the PATCH/POST request.
- Server checks this parameter and if it is true, then it just generates HTML from Markdown and stores it into the `body_preview` field.
- When a save is triggered on the client, we add a `preview: false` as a parameter
- If preview is false, server will
  - Generate `body_preview` from `markdown_preview`
  - **Also store `markdown_preview` into `markdown`**
  - **Also store `body_preview` into `body`**
  - For new posts, set status to `published`
  - Reply with the saved post

### NOTES
- I considered briefly having only 3 fields - `body`, `markdown` and `body_preview`, but that wouldn't really work. We would lose the original markdown if the user decided t abandon the edit.
- **Considering our UI right now, we also need a `title_preview`, since the post is being edited as a whole.** If we want to edit the title separately, then we need to redo our UI and make sure our API is able to do that (I think it is).
- We don't really need a draft field on the client side.

### What we need to test for
- `body` and `markdown` can be nil, as long as `body_preview` and `markdown_preview` are not.
- POST action with `preview: true` should result in creating a new post with `status: draft`, empty `body` and `markdown`, non-empty `_preview` fields. `number` should not be assigned in this case.
- POST action with 'preview: false`should result in creating a new post with`status: published`, non-empty`body`and`markdown`fields, with`_preview`fields set to the same value as the non-preview fields.`number` should be assigned.
- PATCH action with `preview: true` results in only modifying the `preview` fields and responding with the updated record. Number remains untouched.
- PATCH action with `preview: false` where post status is not `draft`. results in modifying both preview and non-preview fields, setting them to the newly updated value. Number remains untouched.
- PATCH action with 'preview:false`if post status is`draft`should make that post a`published`post, and also assign`number`.

## Draft history approach

If we want draft history, then a preview field will not really work. Instead, I'm thinking of a different system altogether.

This would be way more complex, but also more flexible, if properly implemented. I'm thinking we'd store drafts separately from the actual post/comment and copy the latest draft's content into the post/comment only when the user decided to actually save.

I'd really need to think about this one, though.

**Comment by joshsmith** [comment]
@begedin Is this closed because of work we've done so far? Or at least irrelevant given the status of things now?

**Comment by begedin** [comment]
This was supposed to be closed with #219 

There's a bug #246, which is being resolved with #252 , but this one should not depend on it.
