### ISSUE TITLE
Add a slugged endpoint for users/organizations

### ISSUE THREAD

**Issue by joshsmith** [code-corps/deprecated-code-corps-rails-api#39]
We need to implement something like what's implemented here: http://blog.arkency.com/2014/01/short-urls-for-every-route-in-your-rails-app/

You would hit `api.domain.com/:slug` and render either a `User` or an `Organization`. Since there are more users than organizations (i.e. a likelier hit), we should find users first, and then query for organizations before rendering a 404.

**Comment by joshsmith** [comment]
We'll also likely need a matcher for `/:slug/:project_slug`

**Comment by joshsmith** [comment]
Also see this for more explication: http://stackoverflow.com/questions/33837394/rails-same-top-level-url-route-for-organizations-user-domain-com-user-and-domai

**Comment by begedin** [comment]
The rails side seems relatively simple.

The ember side would be the complicated one, but I guess we could do a manual ajax request instead of a `store.find`, followed by figuring out if we got back a user or an organization, pushing it to the store and then and then either redirect to the proper route, or just set the controller model , the type of which determines if we render an organization or a user component. I'm not really sure which one is better in this case, but redirecting to a route would add the additional difficulty of making sure our URL is in the format we'd like it to be.

My question for the rails side is, how would we want to handle our slug?

Is it just a parametrized username/organization.name? Can it be editable? Do we use a gem, such as friendly_id, or just make a slug field and use `find_by_slug`? From what I remember from other projects, when we were using a the friendly id gem, there were some complications we had to deal with, both on the API and Ember side.

If we decide in advance the API will never allow us to fetch a user or an organization by id directly, it might be easier to not use the gem and just add a slug field and always fetch by it.
