### ISSUE TITLE
Add ability to sign up with Github

### ISSUE THREAD

**Issue by joshsmith** [code-corps/deprecated-code-corps-rails-api#72]

**Comment by begedin** [comment]
Trying to wrap my head around this, so making some notes. The approach would be similar as with Facebook.

My assumption is that we want the usual flow, where the user authorizes the app on github and then they get taken back to the register screen, where their info is is filled in and can be edited. 

https://developer.github.com/v3/oauth/

## Ember app
- User decided to register through github. `client_id`, `redirect_uri`, `scope` and `state` need to be provided. Scope should be set to "user", or "user:email" or something appropriate (see link above)
- Once the GitHub side of things is done, we will get a code back
- We use the code, alongside other parameters, including `client_id` and `client_secret` to get back an access token.
- We use the access token to get user information and fill in the form
- Once user agrees on the information and submits, we send the info, alongside the access token, to github. There is no equivalent of `facebook_id`, but I guess we could use the github username for that.

## API
- `users#create` is called and the payload is very similar to regular user creation, which diverges from how facebook does it.
- There's a `github_access_token` and a `github_username` parameter.
- We store those in new db columns for later access
- If params contain an image, then that's it. We save and render the user
- If there is no image, then we call a worker to set the image from GitHub
  - We can use the Octokit gem for this.

**The problem here is that quite a lot needs to be done on the client side to pre-fill the information.** Maybe a good alternative would be to
- I'm pretty sure we still need to get an access token on the client side
- We send the access_token to the API, there we use it and `Octokit` to fill out the user information GitHub has available and then, when the API finally responds, the client APP can redirect to the edit profile route.

**Comment by joshsmith** [comment]
Closed in favor of [#9](https://github.com/code-corps/code-corps-phoenix/issues/9).
