### ISSUE TITLE
Write ProjectPolicy

### ISSUE THREAD

**Issue by joshsmith** [code-corps/deprecated-code-corps-rails-api#94]
We need to do the `index`, `show`, `create`, and `update`.

**Comment by begedin** [comment]
## @JoshSmith I wrote a proposal in the associated PR #114, but here it is, copied in full

## Two general cases

### User is project owner
- The owner needs to be the current user.

### Team is project owner
- The current user needs to belong to the team and be able to define projects for that team. This should depend on their role in the team, so `user.team_memberships.find_by!(team).role`. The problem is, there is currently no such thing as a membership role in our `team_memberships` table.
- If the current user does not belong to the team, it's possible they could belong to the organization who owns the team, and they could have a role in the organization which would still allow them to define projects for that team. Again, this isn't something we have the database for right now. The `organization_memberships` table would require a column for it.

This would mean we need to 
- [ ] Define possible role levels for  `team_memberships` table and add a column to it
- [ ] Define possible role levels for `organization_memberships` table and add a column to it
- [ ] Decide if there's an organization role level which allows the user to create projects for a team they aren't a member off.
